project:
  type: website

website:
  title: "ISSS608-VAA-chl"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise 3"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "Hands-on Exercise 4"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
      - text: "Hands-on Exercise 6"
        href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "Hands-on Exercise 7"
        href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - text: "Hands-on Exercise 9"
        href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
      - text: "In-class Exercise 6 - Heatmap"
        href: "https://public.tableau.com/views/In-class_Ex6-heatmap/Sheet1?:language=en-US&publish=yes&:sid=&:display_count=n&:origin=viz_share_link"
      - text: "In-class Exercise 6 - Tableau Cycle Plot"
        href: "https://public.tableau.com/views/In-class_Ex06_cyclePlot_Arrival/Dashboard1?:language=en-US&publish=yes&:sid=&:display_count=n&:origin=viz_share_link"
      - text: "In-class Exercise 6 - Horizon Plot"
        href: "In-class_Ex/In-class_Ex06/In-class_Ex06_Horizon_Plot.html"
      - text: "In-class Exercise 7"
        href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
      - text: "In-class Exercise 9"
        href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
      - text: "In-class Exercise 10"
        href: "https://public.tableau.com/views/Ex10-CoffeeChain/Dashboard1?:language=en-GB&:sid=&:display_count=n&:origin=viz_share_link"
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
      - text: "Take-home Exercise 2"
      - text: "Take-home Exercise 3"
        href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - text: "Take-home Exercise 4"
        href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
        
    right:  
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united #cosmo
    css: styles.css
    toc: true

editor: visual

